version: '2'
services:
  mongo:
    image: mongo:4.2-bionic
    networks: 
      - internal
    expose:
      - 27017
    restart: always
    volumes:
      - mongo:/data/db
  coin:
    image: battlestarcoin/linux-node
    environment:
      - RPCUSER=${RPCUSER}
      - PRCPASS=${PRCPASS}
      - RPCIP=${RPCIP}
    restart: always
    networks:
      - bridge
      - internal
    ports:
      - 16914:16914
    expose:
      - 59332
    volumes:
      - coin:/home/batl/
    command: ["batld", "-txindex=1"]
  explorer:
    image: battlestarcoin/explorer
    environment:
      - IQUIDUS_SETTINGS={"title":"BattlestarCoin Explorer","address":"https://explorer.domainhere.org","wallet":{"host":"batl","port":16915,"username":"${RPCUSER}","password":"${PRCPASS}"}}
    restart: unless-stopped
    networks:
      - bridge
      - internal
    ports:
      - 3001:3001
    volumes:
      - explorer:/home/iquidus
    depends_on:
      - mongo
      - coin
volumes:
  mongo:
    name: mongo
    driver: local
  coin:
    name: coin
    driver: local
  explorer:
    name: explorer
    driver: local
